#!/usr/bin/env bash
#Install haproxy and configurate both servers

apt-get -y update
apt-get -y install haproxy
cat << EOF >> /etc/haproxy/haproxy.cfg
frontend front
    bind *:80
    mode http
    default_backend back

backend back
    balance roundrobin
    server 487899-web-01 54.158.186.150:80 check
    server 487899-web-02 34.224.1.185:80 check
EOF
service haproxy restart
