#!/usr/bin/env bash
# A bash script that fixes the issues with nginx server problems from listening on port 80.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
